name: direction_guesser
description: "Direction Guesser, the game that you direct!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  camera: ^0.11.0+2
  cross_file_image: ^1.1.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_launcher_icons:
  geolocator: ^13.0.1
  holding_gesture: ^1.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/default_profile_picture.png
